//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "Fasttrap-ETWProvider" event count 4
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = d8909c24-5be9-4502-98ca-ab7bdc24899d
EXTERN_C __declspec(selectany) const GUID ProviderGuid = {0xd8909c24, 0x5be9, 0x4502, {0x98, 0xca, 0xab, 0x7b, 0xdc, 0x24, 0x89, 0x9d}};

#ifndef ProviderGuid_Traits
#define ProviderGuid_Traits NULL
#endif // ProviderGuid_Traits

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Entry = {0x1, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0};
#define Entry_value 0x1
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Return = {0x2, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0};
#define Return_value 0x2
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Events = {0x3, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0};
#define Events_value 0x3
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR Status = {0x4, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0};
#define Status_value 0x4

#define MSG_Provider_Name                    0x90000001L
#define MSG_Event_Entry                      0xB0000001L
#define MSG_Event_Return                     0xB0000002L
#define MSG_Event_Events                     0xB0000003L
#define MSG_Event_Status                     0xB0000004L
