/*
 * Generated by dtrace(1M).
 */

#ifndef	_PROV_H
#define	_PROV_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#if _DTRACE_VERSION

#define	TEST_PROV_GO() \
	__dtrace_test_prov___go()
#ifndef	__sparc
#define	TEST_PROV_GO_ENABLED() \
	__dtraceenabled_test_prov___go()
#else
#define	TEST_PROV_GO_ENABLED() \
	__dtraceenabled_test_prov___go(0)
#endif


extern void __dtrace_test_prov___go(void);
#ifndef	__sparc
extern int __dtraceenabled_test_prov___go(void);
#else
extern int __dtraceenabled_test_prov___go(long);
#endif

#else

#define	TEST_PROV_GO()
#define	TEST_PROV_GO_ENABLED() (0)

#endif


#ifdef	__cplusplus
}
#endif

#endif	/* _PROV_H */
